#!/bin/sh
# Regenerate fe-parse.js from the replayer's parsers.
#
# The analyzer reads the same hand histories the replayer does, so it uses the
# same parsers rather than a second copy that drifts. Run this after changing
# anything under replayer/src/parsers or src/model, then commit the result.
set -e
REPLAYER="${REPLAYER:-$HOME/Desktop/Replayer}"
OUT="$(cd "$(dirname "$0")" && pwd)/fe-parse.js"
ENTRY="$REPLAYER/_fe_parse_entry.ts"

cat > "$ENTRY" <<'TS'
export { parseHandHistory, splitHands, detectSite, ParseError } from './src/parsers/index.ts';
export { positionMap } from './src/model/position.ts';
TS

"$REPLAYER/node_modules/.bin/esbuild" "$ENTRY" \
  --bundle --format=iife --global-name=FEParse --target=es2019 \
  --banner:js="/* Generated by study/build-parsers.sh from the replayer's parsers. Do not edit. */" \
  --outfile="$OUT"
rm -f "$ENTRY"
echo "wrote $OUT"
