/* Generated by study/build-parsers.sh from the replayer's parsers. Do not edit. */
"use strict";
var FEParse = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // ../../Replayer/_fe_parse_entry.ts
  var fe_parse_entry_exports = {};
  __export(fe_parse_entry_exports, {
    ParseError: () => ParseError,
    detectSite: () => detectSite,
    parseHandHistory: () => parseHandHistory,
    positionMap: () => positionMap,
    splitHands: () => splitHands
  });

  // ../../Replayer/src/model/types.ts
  function displayCurrency(sym) {
    return sym === "\xA5" ? "$" : sym;
  }
  function emptyHand(site = "Manual") {
    return {
      site,
      handId: "",
      gameType: "cash",
      variant: "Hold'em No Limit",
      currency: "$",
      sb: 0.5,
      bb: 1,
      ante: 0,
      tableName: "",
      maxSeats: 6,
      buttonSeat: 1,
      players: [],
      posts: [],
      actions: [],
      board: [],
      showdowns: [],
      winnings: [],
      rake: 0,
      warnings: [],
      advisories: []
    };
  }
  var round2 = (n) => Math.round(n * 100) / 100;

  // ../../Replayer/src/parsers/common.ts
  var ParseError = class extends Error {
    constructor(message, lineNumber, line) {
      super(message);
      this.lineNumber = lineNumber;
      this.line = line;
      this.name = "ParseError";
    }
  };
  function parseMoney(s) {
    const v = parseFloat(s.replace(/[$€£¥,\s]/g, ""));
    return Math.round(v * 100) / 100;
  }
  var CARD_RE = /[2-9TJQKA][shdc]/g;
  function parseCards(s) {
    var _a;
    return (_a = s.match(CARD_RE)) != null ? _a : [];
  }
  function splitHands(text) {
    const headerRe = /^(PokerStars|Poker Hand #|Game Hand #|Ignition Hand|Bovada Hand|ClubGG Hand|Hand History driven|[A-Za-z][\w .'-]* Hand #\d+)/;
    const lines = text.split(/\r?\n/);
    const hands = [];
    let cur = null;
    for (const line of lines) {
      if (headerRe.test(line.trim())) {
        cur = [line];
        hands.push(cur);
      } else if (cur) {
        cur.push(line);
      } else if (line.trim() !== "") {
        cur = [line];
        hands.push(cur);
      }
    }
    return hands.map((h) => h.join("\n").trim()).filter((h) => h.length > 0);
  }

  // ../../Replayer/src/parsers/starslike.ts
  var MONEY = String.raw`[$€£¥]?([\d][\d,]*(?:\.\d+)?)`;
  var ALLIN = /\s*and is all[ -]?in/i;
  function parseStarsLike(text, site) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l;
    const lines = text.split(/\r?\n/);
    const hand = emptyHand(site);
    const err = (msg, i2) => {
      throw new ParseError(msg, i2 + 1, lines[i2]);
    };
    let li = 0;
    while (li < lines.length && lines[li].trim() === "") li++;
    const header = (_b = (_a = lines[li]) == null ? void 0 : _a.trim()) != null ? _b : "";
    if (!header) throw new ParseError("Empty hand history.");
    const idMatch = header.match(/#(\w+)/);
    hand.handId = idMatch ? idMatch[1] : "";
    hand.gameType = /Tournament/i.test(header) ? "tournament" : "cash";
    if (hand.gameType === "tournament") {
      const t = header.match(/Tournament #\d+[, -]*(.*?)(?:\s*-\s*Level|\s*-\s*\d{4})/);
      hand.info = t ? t[1].trim() : "Tournament";
    }
    if (!/hold'?em/i.test(header)) {
      hand.warnings.push(`Game type in header may not be Hold'em: "${header}"`);
    }
    const blindMatches = [...header.matchAll(new RegExp(String.raw`\(\s*${MONEY}\s*\/\s*${MONEY}(?:\s*-\s*Ante\s*${MONEY}|\s*\(\s*${MONEY}\s*\))?(?:\s*(?:USD|EUR|GBP|CNY))?\s*\)`, "g"))];
    const bm = blindMatches[blindMatches.length - 1];
    if (bm) {
      hand.sb = parseMoney(bm[1]);
      hand.bb = parseMoney(bm[2]);
      hand.currency = /[$]/.test(bm[0]) || /USD/.test(header) ? "$" : /€|EUR/.test(bm[0] + header) ? "\u20AC" : /¥|CNY|JPY/.test(bm[0] + header) ? "\xA5" : "";
    } else {
      const sbLine = text.match(new RegExp(String.raw`posts small blind\s+${MONEY}`, "i"));
      const bbLine = text.match(new RegExp(String.raw`posts big blind\s+${MONEY}`, "i"));
      if (!sbLine || !bbLine) {
        err("Could not find blinds like ($0.50/$1.00) in the header line.", li);
      }
      hand.sb = parseMoney(sbLine[1]);
      hand.bb = parseMoney(bbLine[1]);
      const sym = sbLine[0] + bbLine[0];
      hand.currency = /[$]/.test(sym) ? "$" : /€/.test(sym) ? "\u20AC" : /¥/.test(sym) ? "\xA5" : "";
      hand.warnings.push("The header line looks incomplete, so the stakes were read from the posted blinds instead.");
    }
    if (hand.gameType === "tournament") hand.currency = "";
    let ti = li + 1;
    while (ti < lines.length && !/^Table/.test(lines[ti].trim())) {
      ti++;
      if (ti - li > 4) break;
    }
    const tline = (_d = (_c = lines[ti]) == null ? void 0 : _c.trim()) != null ? _d : "";
    const tm = tline.match(/^Table\s+'(.*)'\s+(\d+)-max.*Seat #(\d+) is the button/i);
    if (!tm) err("Expected a table line like: Table 'Name' 6-max Seat #3 is the button", Math.min(ti, lines.length - 1));
    hand.tableName = tm[1];
    hand.maxSeats = parseInt(tm[2], 10);
    hand.buttonSeat = parseInt(tm[3], 10);
    let i = ti + 1;
    const seatRe = new RegExp(String.raw`^Seat (\d+):\s+(.+?)\s+\(${MONEY}(?:\s+in chips)?\)\s*(.*)$`);
    for (; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line === "") continue;
      const m = line.match(seatRe);
      if (!m) break;
      hand.players.push({
        seat: parseInt(m[1], 10),
        name: m[2].trim(),
        stack: parseMoney(m[3]),
        cards: null,
        isHero: false,
        sittingOut: /sitting out|out of hand/i.test(m[4])
      });
    }
    if (hand.players.length < 2) err("Found fewer than 2 seats \u2013 is this a complete hand history?", Math.min(i, lines.length - 1));
    const namesByLen = hand.players.map((p) => p.name).sort((a, b) => b.length - a.length);
    const matchPlayer = (line) => {
      for (const n of namesByLen) {
        if (line.startsWith(n)) {
          const rest = line.slice(n.length);
          if (rest === "" || /^[ :]/.test(rest)) return { name: n, rest: rest.replace(/^:?\s*/, "") };
        }
      }
      return null;
    };
    let section = "setup";
    let street = "preflop";
    let run = 0;
    const setBoard = (cards) => {
      if (run === 2) hand.board2 = cards;
      else hand.board = cards;
    };
    const committed = {};
    const resetCommits = () => hand.players.forEach((p) => committed[p.name] = 0);
    resetCommits();
    const pushAct = (a) => hand.actions.push(a);
    for (; i < lines.length; i++) {
      const raw = lines[i];
      const line = raw.trim();
      if (line === "") continue;
      let markName;
      let markRest;
      const starred = line.match(/^\*+\s*([A-Z ]+?)\s*\*+(.*)$/);
      if (starred) {
        markName = starred[1];
        markRest = starred[2];
      } else {
        const bare = line.match(
          /^((?:FIRST|SECOND|THIRD|FOURTH)\s+)?(HOLE CARDS|FLOP|TURN|RIVER|SHOW\s?DOWN|SUMMARY)\s*(\[.*)?$/i
        );
        if (bare) {
          markName = ((_e = bare[1]) != null ? _e : "") + bare[2];
          markRest = bare[3];
        }
      }
      if (markName !== void 0) {
        let name2 = markName.trim();
        const rest2 = markRest != null ? markRest : "";
        const runM = name2.match(/^(FIRST|SECOND|THIRD|FOURTH)\s+(.+)$/i);
        if (runM) {
          const which = runM[1].toUpperCase();
          if (which === "THIRD" || which === "FOURTH") {
            err("Hands run more than twice are not supported yet.", i);
          }
          run = which === "SECOND" ? 2 : 1;
          name2 = runM[2].trim();
        } else if (name2 !== "SUMMARY") {
          run = 0;
        }
        if (name2 === "HOLE CARDS") {
          section = "preflop";
          street = "preflop";
        } else if (name2 === "FLOP") {
          section = street = "flop";
          resetCommits();
          const cards = parseCards(rest2);
          if (cards.length < 3) err("Could not read 3 flop cards from this line.", i);
          setBoard(cards.slice(0, 3));
        } else if (name2 === "TURN") {
          section = street = "turn";
          resetCommits();
          const cards = parseCards(rest2);
          if (cards.length < 4) err("Could not read the turn card from this line.", i);
          setBoard(cards.slice(0, 4));
        } else if (name2 === "RIVER") {
          section = street = "river";
          resetCommits();
          const cards = parseCards(rest2);
          if (cards.length < 5) err("Could not read the river card from this line.", i);
          setBoard(cards.slice(0, 5));
        } else if (/SHOW\s?DOWN/.test(name2)) section = "showdown";
        else if (name2 === "SUMMARY") section = "summary";
        continue;
      }
      let m;
      if (m = line.match(new RegExp(String.raw`^Uncalled bet \(${MONEY}\) returned to (.+)$`))) {
        const player = m[2].trim();
        const amt = parseMoney(m[1]);
        committed[player] = round2(((_f = committed[player]) != null ? _f : 0) - amt);
        pushAct({ street, player, kind: "return", add: amt });
        continue;
      }
      if (m = line.match(new RegExp(String.raw`^(Main|Side) pot(?:[- ]?\d*)? won by (.+?) \(${MONEY}\)`, "i"))) {
        hand.winnings.push({ player: m[2].trim(), amount: parseMoney(m[3]), pot: m[1].toLowerCase() });
        continue;
      }
      if (/^Dealt to /.test(line)) {
        const dm = line.match(/^Dealt to (.+?)\s*\[([^\]]+)\]/);
        if (dm) {
          const p = hand.players.find((x) => x.name === dm[1].trim());
          if (p) {
            p.cards = parseCards(dm[2]);
            if (!hand.players.some((x) => x.isHero)) p.isHero = true;
          }
        }
        continue;
      }
      if (section === "summary") {
        if (m = line.match(new RegExp(String.raw`^Total pot\s+${MONEY}`, "i"))) {
          hand.totalPot = parseMoney(m[1]);
          const rm = line.match(new RegExp(String.raw`Rake\s+${MONEY}`, "i"));
          if (rm) hand.rake = parseMoney(rm[1]);
        }
        if (m = line.match(/^(FIRST|SECOND)\s+Board\s+\[([^\]]+)\]/i)) {
          const cards = parseCards(m[2]);
          if (/^second$/i.test(m[1])) {
            if (((_h = (_g = hand.board2) == null ? void 0 : _g.length) != null ? _h : 0) < cards.length) hand.board2 = cards;
          } else if (hand.board.length < cards.length) hand.board = cards;
          continue;
        }
        if (m = line.match(/^Seat \d+:\s+(.+?)\s+(?:\(.*?\)\s+)?(mucked|showed)\s+\[([^\]]+)\]/)) {
          const p = hand.players.find((x) => x.name === m[1].trim());
          const cards = parseCards(m[3]);
          if (p && !p.cards && cards.length >= 2) p.cards = cards;
          const sd = hand.showdowns.find((s) => s.player === m[1].trim());
          if (sd && !sd.cards) sd.cards = cards;
        }
        continue;
      }
      const pm = matchPlayer(line);
      if (!pm) {
        continue;
      }
      const { name, rest } = pm;
      if (m = rest.match(new RegExp(String.raw`^posts (?:the )?small blind ${MONEY}`, "i"))) {
        hand.posts.push(post(name, "sb", m[1], rest));
        committed[name] = round2(committed[name] + parseMoney(m[1]));
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^posts (?:the )?big blind ${MONEY}`, "i"))) {
        hand.posts.push(post(name, "bb", m[1], rest));
        committed[name] = round2(committed[name] + parseMoney(m[1]));
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^posts (?:the )?ante ${MONEY}`, "i"))) {
        const amt = parseMoney(m[1]);
        hand.posts.push(post(name, "ante", m[1], rest));
        hand.ante = Math.max(hand.ante, amt);
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^posts (?:the )?straddle ${MONEY}`, "i"))) {
        hand.posts.push(post(name, "straddle", m[1], rest));
        committed[name] = round2(committed[name] + parseMoney(m[1]));
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^posts small & big blinds? ${MONEY}`, "i"))) {
        const total = parseMoney(m[1]);
        const dead = round2(total - hand.bb);
        if (dead > 0) hand.posts.push({ player: name, type: "dead", amount: dead });
        hand.posts.push({ player: name, type: "bb", amount: hand.bb });
        committed[name] = round2(committed[name] + hand.bb);
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^posts .*?${MONEY}`, "i"))) {
        hand.posts.push({ player: name, type: "dead", amount: parseMoney(m[1]) });
        continue;
      }
      if (/^folds/i.test(rest)) {
        pushAct({ street, player: name, kind: "fold" });
        continue;
      }
      if (/^checks/i.test(rest)) {
        pushAct({ street, player: name, kind: "check" });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^calls ${MONEY}`, "i"))) {
        const add = parseMoney(m[1]);
        committed[name] = round2(((_i = committed[name]) != null ? _i : 0) + add);
        pushAct({ street, player: name, kind: "call", to: committed[name], add, allIn: ALLIN.test(rest) || void 0 });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^bets ${MONEY}`, "i"))) {
        const amt = parseMoney(m[1]);
        const add = round2(amt - ((_j = committed[name]) != null ? _j : 0));
        committed[name] = amt;
        pushAct({ street, player: name, kind: "bet", to: amt, add, allIn: ALLIN.test(rest) || void 0 });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^raises ${MONEY} to ${MONEY}`, "i"))) {
        const to = parseMoney(m[2]);
        const add = round2(to - ((_k = committed[name]) != null ? _k : 0));
        committed[name] = to;
        pushAct({ street, player: name, kind: "raise", to, add, allIn: ALLIN.test(rest) || void 0 });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^raises (?:to )?${MONEY}`, "i"))) {
        const to = parseMoney(m[1]);
        const add = round2(to - ((_l = committed[name]) != null ? _l : 0));
        committed[name] = to;
        pushAct({ street, player: name, kind: "raise", to, add, allIn: ALLIN.test(rest) || void 0 });
        continue;
      }
      if (m = rest.match(/^shows \[([^\]]+)\]/i)) {
        if (run === 2 && hand.showdowns.some((sd) => sd.player === name)) continue;
        hand.showdowns.push({ player: name, cards: parseCards(m[1]) });
        const p = hand.players.find((x) => x.name === name);
        if (p && !p.cards) p.cards = parseCards(m[1]);
        continue;
      }
      if (/^mucks/i.test(rest) || /^doesn'?t show/i.test(rest)) {
        if (section === "showdown") hand.showdowns.push({ player: name, mucked: true });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^collected ${MONEY} from (?:the )?(main pot|side pot(?:[- ]?\d+)?|pot)`, "i"))) {
        hand.winnings.push({
          player: name,
          amount: parseMoney(m[1]),
          pot: /side/i.test(m[2]) ? "side" : "main",
          ...run ? { run } : {}
        });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^collected ${MONEY}`, "i"))) {
        hand.winnings.push({ player: name, amount: parseMoney(m[1]), ...run ? { run } : {} });
        continue;
      }
      if (/^(is sitting out|sits out|sits down|stands up|has timed out|is disconnected|is connected|leaves the table|joins the table|was removed|will be allowed|said,|shows$)/i.test(rest)) {
        continue;
      }
      if (section !== "setup") {
        err(`Unrecognized action for "${name}": "${rest}"`, i);
      }
    }
    if (!hand.players.some((p) => p.isHero)) {
      const named = hand.players.find((p) => /^hero$/i.test(p.name));
      if (named) named.isHero = true;
    }
    return hand;
  }
  function post(player, type, amt, rest) {
    return { player, type, amount: parseMoney(amt), allIn: ALLIN.test(rest) || void 0 };
  }

  // ../../Replayer/src/parsers/ignition.ts
  var MONEY2 = String.raw`[$€£¥]?([\d][\d,]*(?:\.\d+)?)`;
  function parseIgnition(text) {
    var _a, _b, _c, _d, _e, _f;
    const lines = text.split(/\r?\n/);
    const hand = emptyHand("Ignition");
    const err = (msg, i2) => {
      throw new ParseError(msg, i2 + 1, lines[i2]);
    };
    let li = 0;
    while (li < lines.length && lines[li].trim() === "") li++;
    const header = (_b = (_a = lines[li]) == null ? void 0 : _a.trim()) != null ? _b : "";
    const hm = header.match(/^(?:Ignition|Bovada) Hand #(\d+)/);
    if (hm) {
      hand.handId = hm[1];
      hand.gameType = /TBL#|HOLDEM/i.test(header) && /Tournament|MTT|STT/i.test(header) ? "tournament" : "cash";
      hand.tableName = (_d = ((_c = header.match(/TBL#(\d+)/)) != null ? _c : [])[1]) != null ? _d : "";
    } else {
      hand.gameType = /[$€£¥]/.test(text) ? "cash" : "tournament";
    }
    hand.currency = hand.gameType === "tournament" ? "" : "$";
    let i = hm ? li + 1 : li;
    const seatRe = new RegExp(String.raw`^Seat (\d+):\s+(.+?)\s*(\[ME\])?\s*\(${MONEY2} in chips\)\s*(.*)$`);
    for (; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line === "") continue;
      const m = line.match(seatRe);
      if (!m) break;
      hand.players.push({
        seat: parseInt(m[1], 10),
        name: m[2].trim(),
        stack: parseMoney(m[4]),
        cards: null,
        isHero: !!m[3],
        sittingOut: /sitting out/i.test((_e = m[5]) != null ? _e : "")
      });
    }
    if (hand.players.length < 2) err("Found fewer than 2 seats \u2013 is this a complete hand history?", Math.min(i, lines.length - 1));
    if (hand.players.some((p) => p.seat > 10)) {
      hand.players.forEach((p, idx) => {
        p.seat = idx + 1;
      });
    }
    const dealer = hand.players.find((p) => /^dealer$/i.test(p.name));
    if (dealer) hand.buttonSeat = dealer.seat;
    hand.maxSeats = Math.max(hand.players.length, ...hand.players.map((p) => p.seat));
    let section = "setup";
    let street = "preflop";
    const committed = {};
    let currentBet = 0;
    const resetCommits = () => {
      hand.players.forEach((p) => committed[p.name] = 0);
      currentBet = 0;
    };
    resetCommits();
    for (; i < lines.length; i++) {
      const line = lines[i].trim().replace(/\s*\[ME\]\s*/, " ").replace(/\s{2,}/g, " ");
      if (line === "") continue;
      const marker = line.match(/^\*{3}\s*([A-Z ]+?)\s*\*{3}(.*)$/);
      if (marker) {
        const name2 = marker[1].trim();
        const rest2 = marker[2];
        if (name2 === "HOLE CARDS") {
          section = "preflop";
          street = "preflop";
        } else if (name2 === "FLOP") {
          section = street = "flop";
          resetCommits();
          hand.board = parseCards(rest2).slice(0, 3);
          if (hand.board.length < 3) err("Could not read 3 flop cards.", i);
        } else if (name2 === "TURN") {
          section = street = "turn";
          resetCommits();
          const c = parseCards(rest2);
          if (c.length < 4) err("Could not read the turn card.", i);
          hand.board = c.slice(0, 4);
        } else if (name2 === "RIVER") {
          section = street = "river";
          resetCommits();
          const c = parseCards(rest2);
          if (c.length < 5) err("Could not read the river card.", i);
          hand.board = c.slice(0, 5);
        } else if (/SHOW\s?DOWN/.test(name2)) section = "showdown";
        else if (name2 === "SUMMARY") section = "summary";
        continue;
      }
      if (section === "summary") {
        let m2;
        if (m2 = line.match(new RegExp(String.raw`^Total Pot\s*\(?${MONEY2}\)?`, "i"))) {
          hand.totalPot = parseMoney(m2[1]);
        }
        continue;
      }
      const cm = line.match(/^(.+?)\s*:\s*(.*)$/);
      if (!cm) continue;
      const name = cm[1].trim();
      const rest = cm[2].trim();
      const player = hand.players.find((p) => p.name === name);
      if (!player) continue;
      let m;
      if (m = rest.match(new RegExp(String.raw`^Small [Bb]lind ${MONEY2}`))) {
        hand.posts.push({ player: name, type: "sb", amount: parseMoney(m[1]) });
        hand.sb = parseMoney(m[1]);
        committed[name] = round2(committed[name] + parseMoney(m[1]));
        currentBet = Math.max(currentBet, committed[name]);
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^Big [Bb]lind ${MONEY2}`))) {
        hand.posts.push({ player: name, type: "bb", amount: parseMoney(m[1]) });
        hand.bb = parseMoney(m[1]);
        committed[name] = round2(committed[name] + parseMoney(m[1]));
        currentBet = Math.max(currentBet, committed[name]);
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^Ante chip ${MONEY2}`, "i"))) {
        const amt = parseMoney(m[1]);
        hand.posts.push({ player: name, type: "ante", amount: amt });
        hand.ante = Math.max(hand.ante, amt);
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^Posts? straddle ${MONEY2}`, "i"))) {
        hand.posts.push({ player: name, type: "straddle", amount: parseMoney(m[1]) });
        committed[name] = round2(committed[name] + parseMoney(m[1]));
        currentBet = Math.max(currentBet, committed[name]);
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^Posts? (?:dead )?chip ${MONEY2}`, "i"))) {
        hand.posts.push({ player: name, type: "dead", amount: parseMoney(m[1]) });
        continue;
      }
      if (m = rest.match(/^Card dealt to a spot \[([^\]]+)\]/i)) {
        player.cards = parseCards(m[1]);
        continue;
      }
      if (/^Set dealer/i.test(rest) || /^Set deale/i.test(rest)) {
        const dm = rest.match(/\[(\d+)\]/);
        if (dm && !dealer) hand.buttonSeat = parseInt(dm[1], 10);
        continue;
      }
      if (/^Folds?\b/i.test(rest)) {
        hand.actions.push({ street, player: name, kind: "fold" });
        continue;
      }
      if (/^Checks?\b/i.test(rest)) {
        hand.actions.push({ street, player: name, kind: "check" });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^Calls? ${MONEY2}`))) {
        const add = parseMoney(m[1]);
        committed[name] = round2(committed[name] + add);
        hand.actions.push({ street, player: name, kind: "call", to: committed[name], add });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^Bets? ${MONEY2}`))) {
        const amt = parseMoney(m[1]);
        const add = round2(amt - committed[name]);
        committed[name] = amt;
        currentBet = Math.max(currentBet, amt);
        hand.actions.push({ street, player: name, kind: "bet", to: amt, add });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^(?:All-in\(raise(?:-timeout)?\)|Raises?) ${MONEY2} to ${MONEY2}`, "i"))) {
        const to = parseMoney(m[2]);
        const add = round2(to - committed[name]);
        committed[name] = to;
        currentBet = Math.max(currentBet, to);
        hand.actions.push({ street, player: name, kind: "raise", to, add, allIn: /^All-in/i.test(rest) || void 0 });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^All-in ${MONEY2}`, "i"))) {
        const add = parseMoney(m[1]);
        const to = round2(committed[name] + add);
        const kind = to > currentBet ? currentBet > 0 ? "raise" : "bet" : "call";
        committed[name] = to;
        currentBet = Math.max(currentBet, to);
        hand.actions.push({ street, player: name, kind, to, add, allIn: true });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^Return uncalled portion of bet ${MONEY2}`, "i"))) {
        const amt = parseMoney(m[1]);
        committed[name] = round2(committed[name] - amt);
        hand.actions.push({ street, player: name, kind: "return", add: amt });
        continue;
      }
      if (m = rest.match(/^Showdown/i)) {
        hand.showdowns.push({ player: name, cards: (_f = player.cards) != null ? _f : void 0 });
        continue;
      }
      if (m = rest.match(/^Mucks/i)) {
        const mc = rest.match(/\[([^\]]+)\]/);
        hand.showdowns.push({ player: name, mucked: true, cards: mc ? parseCards(mc[1]).slice(0, 2) : void 0 });
        continue;
      }
      if (m = rest.match(new RegExp(String.raw`^Hand result(-Side pot)? ${MONEY2}`, "i"))) {
        hand.winnings.push({ player: name, amount: parseMoney(m[2]), pot: m[1] ? "side" : "main" });
        continue;
      }
      if (/^(Table (enter|leave|deposit)|Seat (sit out|sit down|re-join|stand)|Sit out|Sitout|Leave|Enters|Stand|Timeout|Does not show)/i.test(rest)) {
        continue;
      }
      if (section !== "setup") err(`Unrecognized action for "${name}": "${rest}"`, i);
    }
    if (hand.totalPot && hand.winnings.length > 0) {
      const paid = hand.winnings.reduce((a, w) => a + w.amount, 0);
      const returned = hand.actions.filter((a) => a.kind === "return").reduce((a, x) => {
        var _a2;
        return a + ((_a2 = x.add) != null ? _a2 : 0);
      }, 0);
      const rake = round2(hand.totalPot - returned - paid);
      if (rake > 0) hand.rake = rake;
    }
    return hand;
  }

  // ../../Replayer/src/model/pot.ts
  function uncalledRefund(contribs) {
    const entries = Object.entries(contribs);
    if (entries.length < 2) return null;
    entries.sort((a, b) => b[1] - a[1]);
    const diff = round2(entries[0][1] - entries[1][1]);
    if (diff > 0) return { player: entries[0][0], amount: diff };
    return null;
  }

  // ../../Replayer/src/parsers/drivehud.ts
  var RINGS = {
    2: ["SB", "BB"],
    3: ["SB", "BB", "BTN"],
    4: ["SB", "BB", "CO", "BTN"],
    5: ["SB", "BB", "MP", "CO", "BTN"],
    6: ["SB", "BB", "UTG", "MP", "CO", "BTN"],
    7: ["SB", "BB", "UTG", "UTG_1", "MP", "CO", "BTN"],
    8: ["SB", "BB", "UTG", "UTG_1", "MP", "MP_1", "CO", "BTN"],
    9: ["SB", "BB", "UTG", "UTG_1", "UTG_2", "MP", "MP_1", "CO", "BTN"]
  };
  var SLOT_ALIASES = { MP: ["MP", "HJ"] };
  var slotTokens = (slot) => {
    var _a;
    return (_a = SLOT_ALIASES[slot]) != null ? _a : [slot];
  };
  var pretty = (token) => token === "HERO" ? "Hero" : token.replace(/_/g, "+");
  var TOKEN = String.raw`[A-Z][A-Z_0-9]*`;
  var AMT = String.raw`\$?([\d][\d,]*(?:\.\d+)?)`;
  function parseDriveHud(text) {
    var _a, _b, _c;
    const lines = text.split(/\r?\n/).map((l) => l.trim());
    const hand = emptyHand("DriveHUD");
    hand.currency = "$";
    hand.tableName = "DriveHUD export";
    const err = (msg, i2) => {
      throw new ParseError(msg, i2 + 1, lines[i2]);
    };
    let si = lines.findIndex((l) => /^NL Hold'?em\s+[\d.]+\s*\(BB\)/i.test(l));
    if (si < 0) throw new ParseError('Expected a stakes line like "NL Holdem 0.2(BB)" in the DriveHUD export.');
    hand.bb = parseMoney(lines[si].match(/([\d.]+)\s*\(BB\)/i)[1]);
    hand.sb = round2(hand.bb / 2);
    const rows = [];
    let i = si + 1;
    const playerRe = new RegExp(String.raw`^(${TOKEN})\s*\(${AMT}\)`);
    for (; i < lines.length; i++) {
      const line = lines[i];
      if (line === "") continue;
      if (/^Dealt to/i.test(line)) break;
      const m = line.match(playerRe);
      if (m) rows.push({ token: m[1], stack: parseMoney(m[2]) });
      else break;
    }
    const n = rows.length;
    const ring = RINGS[n];
    if (!ring) err(`Found ${n} players \u2013 expected between 2 and 9.`, si);
    const present = new Set(rows.map((r) => r.token));
    const hasSlot = (slot) => slotTokens(slot).some((t) => present.has(t));
    let heroPos = null;
    if (present.has("HERO")) {
      heroPos = (_a = ring.find((p) => !hasSlot(p))) != null ? _a : null;
      if (!heroPos) err("Could not work out which position HERO occupies.", si);
    }
    for (const pos of ring) {
      if (!hasSlot(pos) && pos !== heroPos) {
        err(`Player list doesn't match a ${n}-handed table (missing ${pos}).`, si);
      }
    }
    ring.forEach((pos, idx) => {
      const row = pos === heroPos ? rows.find((r) => r.token === "HERO") : rows.find((r) => slotTokens(pos).includes(r.token));
      hand.players.push({
        seat: idx + 1,
        name: pretty(row.token),
        stack: row.stack,
        cards: null,
        isHero: row.token === "HERO",
        sittingOut: false
      });
    });
    hand.maxSeats = n;
    hand.buttonSeat = n === 2 ? 1 : ring.indexOf("BTN") + 1;
    const heroTokens = /* @__PURE__ */ new Set(["HERO", ...heroPos ? slotTokens(heroPos) : []]);
    const nameOf = (token) => {
      if (heroTokens.has(token)) return "Hero";
      return pretty(token);
    };
    const sbName = hand.players[ring.indexOf("SB")].name;
    const bbName = hand.players[ring.indexOf("BB")].name;
    const bodyStart = i;
    const replay = (ante2) => {
      const posts = [];
      const actions = [];
      const showdowns = [];
      const winnings = [];
      let board = [];
      const checks = [];
      let street = "preflop";
      const committed = {};
      const stackLeft = {};
      const contrib = {};
      for (const p of hand.players) {
        committed[p.name] = 0;
        stackLeft[p.name] = p.stack;
        contrib[p.name] = 0;
      }
      let currentBet = 0;
      const spend = (name, add) => {
        add = Math.min(add, stackLeft[name]);
        stackLeft[name] = round2(stackLeft[name] - add);
        committed[name] = round2(committed[name] + add);
        contrib[name] = round2(contrib[name] + add);
        return add;
      };
      const ply = (name, amt) => {
        const add = Math.min(amt, stackLeft[name]);
        stackLeft[name] = round2(stackLeft[name] - add);
        contrib[name] = round2(contrib[name] + add);
        return add;
      };
      if (ante2 > 0) {
        for (const p of hand.players) posts.push({ player: p.name, type: "ante", amount: ply(p.name, ante2) });
      }
      posts.push({ player: sbName, type: "sb", amount: hand.sb });
      posts.push({ player: bbName, type: "bb", amount: hand.bb });
      spend(sbName, hand.sb);
      spend(bbName, hand.bb);
      currentBet = hand.bb;
      const potNow = () => round2(Object.values(contrib).reduce((a, b) => a + b, 0));
      const streetRe = /^(Flop|Turn|River)\s*\(\$?([\d,.]+)\)\s*:\s*(.*)$/i;
      const showRe = new RegExp(String.raw`^(${TOKEN}|Hero)\s+shows:?\s+(.+)$`, "i");
      const winRe = new RegExp(String.raw`^(${TOKEN}|Hero)\s+wins:?\s*${AMT}`, "i");
      const actRe = new RegExp(String.raw`^(${TOKEN}|Hero)\s+(Folds|Checks|Calls|Bets|Raises\s+To|Raises|All-?In)(?:\s+${AMT})?`, "i");
      for (let i2 = bodyStart; i2 < lines.length; i2++) {
        const line = lines[i2];
        if (line === "") continue;
        if (/^NL Hold'?em\s+[\d.]+\s*\(BB\)/i.test(line)) break;
        let m;
        if (m = line.match(/^Dealt to (?:Hero|HERO):?\s*(.+)$/i)) {
          const hero = hand.players.find((p) => p.isHero);
          if (hero) hero.cards = parseCards(m[1]).slice(0, 2);
          continue;
        }
        if (m = line.match(streetRe)) {
          const name = m[1].toLowerCase();
          const stated = parseMoney(m[2]);
          for (const k of Object.keys(committed)) committed[k] = 0;
          currentBet = 0;
          street = name;
          const cards = parseCards(m[3]);
          const need = name === "flop" ? 3 : name === "turn" ? 4 : 5;
          board = cards.length >= need ? cards.slice(0, need) : [...board, ...cards].slice(0, need);
          if (board.length < need) err(`Could not read the ${name} cards.`, i2);
          checks.push({ street: name, stated, recon: potNow() });
          continue;
        }
        if (m = line.match(showRe)) {
          const name = nameOf(m[1]);
          const cards = parseCards(m[2]).slice(0, 2);
          showdowns.push({ player: name, cards });
          const p = hand.players.find((x) => x.name === name);
          if (p && !p.cards) p.cards = cards;
          continue;
        }
        if (m = line.match(winRe)) {
          winnings.push({ player: nameOf(m[1]), amount: parseMoney(m[2]) });
          continue;
        }
        if (actRe.test(line)) {
          for (const rawPart of line.split(/,\s*/)) {
            const part = rawPart.trim();
            if (!part) continue;
            const rem = part.match(/\(Rem\. Stack:\s*\$?([\d,.]+)\)/i);
            const am = part.replace(/\(Rem\. Stack:[^)]*\)/i, "").trim().match(actRe);
            if (!am) {
              if (/^\(/.test(part)) continue;
              err(`Unrecognized action: "${part}"`, i2);
            }
            const name = nameOf(am[1]);
            if (!hand.players.some((p) => p.name === name)) err(`Unknown player "${am[1]}" in action line.`, i2);
            const verb = am[2].toLowerCase().replace(/\s+/g, " ");
            const amount = am[3] != null ? parseMoney(am[3]) : void 0;
            const allInByRem = rem ? parseMoney(rem[1]) === 0 : false;
            if (verb === "folds") {
              actions.push({ street, player: name, kind: "fold" });
            } else if (verb === "checks") {
              actions.push({ street, player: name, kind: "check" });
            } else if (verb === "calls") {
              const toCall = round2(currentBet - committed[name]);
              const add = spend(name, toCall > 0 ? toCall : amount != null ? amount : 0);
              actions.push({
                street,
                player: name,
                kind: "call",
                to: committed[name],
                add,
                allIn: stackLeft[name] === 0 || allInByRem || void 0
              });
            } else if (verb === "bets" || verb === "raises to" || verb === "raises") {
              const printed = amount != null ? amount : 0;
              const to = street === "preflop" && verb !== "bets" ? round2(printed - ante2) : printed;
              const add = spend(name, round2(to - committed[name]));
              currentBet = Math.max(currentBet, committed[name]);
              actions.push({
                street,
                player: name,
                kind: verb === "bets" ? "bet" : "raise",
                to: committed[name],
                add,
                allIn: stackLeft[name] === 0 || allInByRem || void 0
              });
            } else {
              const add = spend(name, amount != null ? amount : stackLeft[name]);
              const to = committed[name];
              const kind = to > currentBet ? currentBet > 0 ? "raise" : "bet" : "call";
              currentBet = Math.max(currentBet, to);
              actions.push({ street, player: name, kind, to, add, allIn: true });
            }
          }
          continue;
        }
      }
      return { posts, actions, showdowns, winnings, board, contrib, checks };
    };
    const fits = (r) => r.checks.every((c) => Math.abs(c.stated - c.recon) <= 0.011);
    let chosen = replay(0);
    let ante = 0;
    if (!fits(chosen) && chosen.checks.length > 0) {
      const probe = replay(1);
      const slope = probe.checks[0].recon - chosen.checks[0].recon;
      if (Math.abs(slope) > 1e-9) {
        const guess = round2((chosen.checks[0].stated - chosen.checks[0].recon) / slope);
        if (guess > 0 && guess <= hand.bb) {
          const withAnte = replay(guess);
          if (fits(withAnte)) {
            chosen = withAnte;
            ante = guess;
          }
        }
      }
    }
    hand.ante = ante;
    hand.posts = chosen.posts;
    hand.actions = chosen.actions;
    hand.showdowns = chosen.showdowns;
    hand.winnings = chosen.winnings;
    hand.board = chosen.board;
    for (const s of chosen.showdowns) {
      const p = hand.players.find((x) => x.name === s.player);
      if (p && !p.cards && s.cards) p.cards = s.cards;
    }
    if (ante > 0) {
      ((_b = hand.advisories) != null ? _b : hand.advisories = []).push(
        `DriveHUD's export doesn't record antes, so the ${hand.currency}${ante.toFixed(2)} ante was worked out from its stated pots and checked against every street. Preflop raise amounts have had the raiser's own ante removed.`
      );
    }
    const off = chosen.checks.find((c) => Math.abs(c.stated - c.recon) > 0.011);
    if (off) {
      ((_c = hand.advisories) != null ? _c : hand.advisories = []).push(
        `DriveHUD converts club currency to $ with rounding \u2013 its stated ${off.street} pot ($${off.stated.toFixed(2)}) differs slightly from the reconstructed pot ($${off.recon.toFixed(2)}). Amounts may be off by a few cents.`
      );
    }
    const potTotal = round2(Object.values(chosen.contrib).reduce((a, b) => a + b, 0));
    const ref = uncalledRefund(chosen.contrib);
    const uncalled = ref ? ref.amount : 0;
    if (hand.winnings.length > 0) {
      const paid = hand.winnings.reduce((a, w) => a + w.amount, 0);
      const rake = round2(potTotal - uncalled - paid);
      if (rake > 0) hand.rake = rake;
    }
    hand.totalPot = round2(potTotal - uncalled);
    return hand;
  }

  // ../../Replayer/src/parsers/index.ts
  function detectSite(text) {
    const head = text.trimStart().slice(0, 200);
    if (/^PokerStars/.test(head)) return "PokerStars";
    if (/^Poker Hand #/.test(head)) return "GGPoker";
    if (/^Game Hand #/.test(head)) return "ACR";
    if (/^(Ignition|Bovada) Hand/.test(head)) return "Ignition";
    if (/^ClubGG Hand/.test(head)) return "ClubGG";
    if (/^Hand History driven/i.test(head) || /DriveHUD/i.test(head) || /^NL Hold'?em\s+[\d.]+\s*\(BB\)/im.test(head)) return "DriveHUD";
    if (/^[A-Za-z][\w .'-]* Hand #\d+.*hold'?em/i.test(head)) return "Other";
    const ignitionish = /^\s*.+\s*:\s*Card dealt to a spot \[/im.test(text) && (/\[ME\]/.test(text) || /:\s*Set dealer/i.test(text) || /:\s*Ante chip /i.test(text));
    if (ignitionish) return "Ignition";
    const hasSeats = /^Seat \d+:\s+.+\(.*(?:in chips|chips)\)/im.test(text);
    const hasBlind = /posts (?:small|big) blind/i.test(text);
    const hasHole = /^\**\s*HOLE CARDS\s*\**$/im.test(text);
    if (hasSeats && hasBlind && hasHole) return "Other";
    return null;
  }
  function parseHandHistory(text) {
    var _a, _b;
    const seats = (_a = text.match(/Seat \d+:/g)) != null ? _a : [];
    if (seats.length >= 2 && text.split("\n").filter((l) => l.trim()).length < 3) {
      throw new ParseError(
        "This hand lost its line breaks somewhere \u2014 it arrived as one long line. Copy it from your poker client or hand history file rather than from a chat message."
      );
    }
    const chunks = splitHands(text);
    if (chunks.length === 0) throw new ParseError("No hand history found in the pasted text.");
    const detectable = chunks.filter((c) => detectSite(c));
    const first = (_b = detectable[0]) != null ? _b : chunks[0];
    const site = detectSite(first);
    if (!site) {
      throw new ParseError(
        "Could not detect the hand history format. Supported: PokerStars, GGPoker (PokerCraft), ACR/WPN, Ignition/Bovada, ClubGG, and converter exports (DriveHUD, Asian Hand Converter).",
        1,
        first.split("\n")[0]
      );
    }
    const hand = site === "Ignition" ? parseIgnition(first) : site === "DriveHUD" ? parseDriveHud(first) : parseStarsLike(first, site);
    hand.currency = displayCurrency(hand.currency);
    return { hand, totalHands: Math.max(detectable.length, 1) };
  }

  // ../../Replayer/src/model/position.ts
  function positionLabels(n) {
    switch (n) {
      case 2:
        return ["BTN", "BB"];
      case 3:
        return ["BTN", "SB", "BB"];
      case 4:
        return ["BTN", "SB", "BB", "CO"];
      case 5:
        return ["BTN", "SB", "BB", "UTG", "CO"];
      case 6:
        return ["BTN", "SB", "BB", "UTG", "HJ", "CO"];
      case 7:
        return ["BTN", "SB", "BB", "UTG", "LJ", "HJ", "CO"];
      case 8:
        return ["BTN", "SB", "BB", "UTG", "UTG+1", "LJ", "HJ", "CO"];
      case 9:
        return ["BTN", "SB", "BB", "UTG", "UTG+1", "UTG+2", "LJ", "HJ", "CO"];
      default:
        return [];
    }
  }
  function positionMap(hand) {
    const active = hand.players.filter((p) => !p.sittingOut);
    const labels = positionLabels(active.length);
    const map = {};
    for (const p of hand.players) if (p.sittingOut) map[p.name] = "OUT";
    if (labels.length === 0) return map;
    const sorted = [...active].sort((a, b) => a.seat - b.seat);
    let btnIdx = sorted.findIndex((p) => p.seat === hand.buttonSeat);
    if (btnIdx < 0) {
      btnIdx = sorted.findIndex((p) => p.seat > hand.buttonSeat);
      if (btnIdx < 0) btnIdx = 0;
      btnIdx = (btnIdx - 1 + sorted.length) % sorted.length;
    }
    for (let i = 0; i < sorted.length; i++) {
      map[sorted[(btnIdx + i) % sorted.length].name] = labels[i];
    }
    return map;
  }
  return __toCommonJS(fe_parse_entry_exports);
})();
